### ISSUE TITLE
Update version number in cookdsp/cookdsp.jsfx-inc

### ISSUE THREAD

**Issue by lossius** [belangeo/cookdsp#3]
Considering the info on verison 0.3 on [this page](http://ajaxsoundstudio.com/software/cookdsp/) I'm wondering if the version number on line 74 of cookdsp/cookdsp.jsfx-inc should be updated to 0.3? Currently it is

```
COOKDSP_VERSION = 0.2;
```

Thanks for a great library BTW, I use it a lot.

**Comment by belangeo** [comment]
Done!
